server:
  port: 18080

spring:
  application:
    name: config-service
  cloud:
    config:
      server:
        native:
          search-locations: classpath:config-repo

eureka:
  client:
    service-url:
      defaultZone: http://eureka-server:8761/eureka
